FROM amsterdam/docker_python:latest
MAINTAINER datapunt@amsterdam.nl

# Install api service in /app folder
WORKDIR /app

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt
RUN rm requirements.txt
RUN rm -rf /app/src/gobcore/tests

# Copy gob api module
COPY gobapi gobapi

# Copy tests
COPY tests tests
COPY .flake8 .flake8
COPY test.sh test.sh

# Copy jenkins files
COPY .jenkins /.jenkins
