FROM amsterdam/python:3.7-buster
MAINTAINER datapunt@amsterdam.nl

# Install ANTLR
RUN apt-get update -y
RUN apt-get install -y antlr4

# Install api service in /app folder
WORKDIR /app

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir -r requirements.txt
RUN rm requirements.txt
RUN rm -rf /app/src/gobcore/tests
RUN rm -rf /app/src/flask-audit-log/tests

# Copy gob api module
COPY gobapi gobapi

# Copy tests
COPY tests tests
COPY .flake8 .flake8
COPY .coveragerc .coveragerc
COPY test.sh test.sh

# Build
COPY build.sh /app
RUN ./build.sh

# Copy jenkins files
COPY .jenkins /.jenkins
